name: masoneer
description: A TUI for managing and generating Mason bricks from multiple GitHub repositories.
version: 1.1.0
repository: https://github.com/Zerkley/masoneer
homepage: https://github.com/Zerkley/masoneer

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  commander_ui: ^2.4.0
  http: ^1.6.0
  toml: ^0.17.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
